<a href="https://colab.research.google.com/github/Charan832844/EDA-project-1/blob/main/25BAI0088_EDA2_ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df1AS =  pd.DataFrame({ 'Jersey Number': [7, 10, 18, 45, 33, 11, 17, 8, 1, 42, 48],
                       'Average Score' : [98, 66, 31, 51, 28, 56, 48, 32, 52, 73, 92]})
df2AS =  pd.DataFrame({'Jersey Number': [2, 4, 6, 28, 10, 12, 14, 16, 38, 20],
                       'Average Score': [98, 93, 44, 77, 69, 56, 31, 53, 78, 93]})

df1HD =  pd.DataFrame({ 'Jersey Number': [7, 10, 18, 45, 33, 11, 17, 8, 1, 42, 48],
                       'Hundreds' : [39, 49, 55, 77, 52, 86, 41, 77, 73, 51, 86]})
df2HD =  pd.DataFrame({'Jersey Number': [2, 4, 6, 28, 10, 12, 14, 16, 38, 20],
                       'Hundreds': [93, 44, 78, 97, 87, 89, 39, 43, 88, 78]})

In [ ]:
dfSE = pd.concat([df1AS, df2AS], ignore_index=True)
dfML = pd.concat([df1HD, df2HD], ignore_index=True)


df = pd.concat([dfML, dfSE], axis=1)
df

    Jersey Number  Hundreds  Jersey Number  Average Score
0               7        39              7             98
1              10        49             10             66
2              18        55             18             31
3              45        77             45             51
4              33        52             33             28
5              11        86             11             56
6              17        41             17             48
7               8        77              8             32
8               1        73              1             52
9              42        51             42             73
10             48        86             48             92
11              2        93              2             98
12              4        44              4             93
13              6        78              6             44
14              8        97              8             77
15             10        87             10             69
16             12        89             12             56
17             14        39             14             31
18             16        43             16             53
19             18        88             18             78
20             20        78             20             93

In [ ]:
dfSE = pd.concat([df1AS, df2AS], ignore_index=True)
dfML = pd.concat([df1HD, df2HD], ignore_index=True)

df = dfSE.merge(dfML, how='inner')
df

    Jersey Number  Average Score  Hundreds
0               7             98        39
1              10             66        49
2              10             66        87
3              18             31        55
4              18             31        88
5              45             51        77
6              33             28        52
7              11             56        86
8              17             48        41
9               8             32        77
10              8             32        97
11              1             52        73
12             42             73        51
13             48             92        86
14              2             98        93
15              4             93        44
16              6             44        78
17              8             77        77
18              8             77        97
19             10             69        49
20             10             69        87
21             12             56        89
22             14             31        39
23             16             53        43
24             18             78        55
25             18             78        88
26             20             93        78

In [ ]:
dfSE = pd.concat([df1AS, df2AS], ignore_index=True)
dfML = pd.concat([df1HD, df2HD], ignore_index=True)

df = dfSE.merge(dfML, how='left')
df

    Jersey Number  Average Score  Hundreds
0               7             98        39
1              10             66        49
2              10             66        87
3              18             31        55
4              18             31        88
5              45             51        77
6              33             28        52
7              11             56        86
8              17             48        41
9               8             32        77
10              8             32        97
11              1             52        73
12             42             73        51
13             48             92        86
14              2             98        93
15              4             93        44
16              6             44        78
17              8             77        77
18              8             77        97
19             10             69        49
20             10             69        87
21             12             56        89
22             14             31        39
23             16             53        43
24             18             78        55
25             18             78        88
26             20             93        78

In [ ]:
dfSE = pd.concat([df1AS, df2AS], ignore_index=True)
dfML = pd.concat([df1HD, df2HD], ignore_index=True)

df = dfSE.merge(dfML, how='right')
df

    Jersey Number  Average Score  Hundreds
0               7             98        39
1              10             66        49
2              10             69        49
3              18             31        55
4              18             78        55
5              45             51        77
6              33             28        52
7              11             56        86
8              17             48        41
9               8             32        77
10              8             77        77
11              1             52        73
12             42             73        51
13             48             92        86
14              2             98        93
15              4             93        44
16              6             44        78
17              8             32        97
18              8             77        97
19             10             66        87
20             10             69        87
21             12             56        89
22             14             31        39
23             16             53        43
24             18             31        88
25             18             78        88
26             20             93        78